package com.netsensia.rivalchess.consts

const val BITBOARD_NONE = -1
const val BITBOARD_WP = 0
const val BITBOARD_WN = 1
const val BITBOARD_WB = 2
const val BITBOARD_WQ = 3
const val BITBOARD_WK = 4
const val BITBOARD_WR = 5
const val BITBOARD_BP = 6
const val BITBOARD_BN = 7
const val BITBOARD_BB = 8
const val BITBOARD_BQ = 9
const val BITBOARD_BK = 10
const val BITBOARD_BR = 11
const val BITBOARD_ALL = 12
const val BITBOARD_FRIENDLY = 13
const val BITBOARD_ENEMY = 14
const val BITBOARD_ENPASSANTSQUARE = 15
const val BITBOARD_COUNT = 16

val whiteBitboardTypes = intArrayOf(BITBOARD_WP, BITBOARD_WN, BITBOARD_WB, BITBOARD_WR, BITBOARD_WQ, BITBOARD_WK)
val blackBitboardTypes = intArrayOf(BITBOARD_BP, BITBOARD_BN, BITBOARD_BB, BITBOARD_BR, BITBOARD_BQ, BITBOARD_BK)
val allBitboardTypes = intArrayOf(BITBOARD_WP,BITBOARD_BP,BITBOARD_WN,BITBOARD_BN,BITBOARD_WB,BITBOARD_BB,
        BITBOARD_WR,BITBOARD_BR,BITBOARD_WQ,BITBOARD_BQ,BITBOARD_WK,BITBOARD_BK
)
