package com.netsensia.rivalchess.config

const val MAX_EXTENSION_DEPTH = 60
const val FRACTIONAL_EXTENSION_FULL = 12
const val MAX_FRACTIONAL_EXTENSIONS = MAX_EXTENSION_DEPTH * FRACTIONAL_EXTENSION_FULL

// 6-12-9
const val FRACTIONAL_EXTENSION_THREAT = 6
const val FRACTIONAL_EXTENSION_PAWNPUSH = 12
const val FRACTIONAL_EXTENSION_CHECK = 6

const val LAST_EXTENSION_LAYER = 4

val maxNewExtensionsTreePart = intArrayOf(12, 9, 6, 3, 0)
