package com.netsensia.rivalchess.config

const val HISTORY_MAX_VALUE = 20000
const val ASPIRATION_RADIUS = 40
const val DELTA_PRUNING_MARGIN = 200
const val MAXIMUM_HASH_AGE = 3
const val NULLMOVE_REDUCE_DEPTH = 2
const val NULLMOVE_DEPTH_REMAINING_FOR_RD_INCREASE = 4
const val NULLMOVE_MINIMUM_FRIENDLY_PIECEVALUES = 550
const val PV_MINIMUM_DISTANCE_FROM_LEAF = 2
const val ADDITIONAL_HASHENTRY_VERIFICATION = false
